trigger:
- main

variables: 
  USERNAME: $(DOCKER_USERNAME)
  PASSWORD: $(DOCKER_PASSWORD)

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Build docker image'
  inputs:
    filePath: 'build.sh'
  env:
    D_USERNAME: $(USERNAME)
    D_PASSWORD: $(PASSWORD)
  