apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerlatest-#{namespace}#
  namespace:#{namespace}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerlatest-#{namespace}#
  template:
    metadata:
      labels:
        app: customerlatest-#{namespace}#
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: customerlatest
        image: arytic.azurecr.io/customerlatest:#{Build.BuildId}#
        resources:
          limits:
            cpu: "0.05"
            memory: 100M
          requests:
            cpu: "0.025"
            memory: 100M
        env:
        - name: Identity_URL
          value: "https://identityapi#{host}#arytic.com"
        - name: Email_URL
          value: "https://emailapi#{host}#arytic.com"
        - name: Jobs_URL
          value: "https://jobsapi#{host}#arytic.com"
        - name: Profile_URL
          value: "https://profileapi#{host}#arytic.com"
        - name: Referral_URL
          value: "https://referalapi#{host}#arytic.com"
        - name: Main_URL
          value: "https://#{basehost}#arytic.co"
        - name: CuMain_URL
          value: "https://customer#{host}#arytic.com"
        - name: CaMain_URL
          value: "https://candidate#{host}#arytic.com"
        - name: Sharing_URL
          value: "https://socialapi#{host}#arytic.com"
        - name: Question_URL
          value: "https://questionnaireapi#{host}#arytic.com"
        - name: Pricing_URL
          value: "https://pricingapi#{host}#arytic.com"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registrysecret
---
apiVersion: v1
kind: Service
metadata:
  name: customer-svc-#{namespace}#
spec:
  ports:
  - port: 80
  selector:
    app: customerlatest-#{namespace}#
    

