import { JobActivity } from "./JobActivity";
import { EducationDetails } from "./educationdetails";
import { JobLocations } from "./joblocations";


export class Jobs {
  public CustomerId: string;
  public SavedJobId: string;
  public JobInfoId: string;
  public JobId: string;
  public ReferralId: string;
  public JobPositionId: string;
  public UserId: string;
  public ResumeId: string;
  public JobResponseId: string;
  public ReferredByUser: string;
  public JobTitle: string;
  public MinExperience: string;
  public MaxExperience: string;
  public JobDescription: string;
  public SkillsRequired: string;
  public EmploymentType: string;
  public ToolsRequired: string;
  public FunctionalArea: string;
  public TotalJobCount: string;
  public FunctionalAreaName: string;
  public JobRole: string; 
  public MinimumSalary: string;
  public MaximumSalary: string;
  public SalaryType: string;
  public CompanyName: string;
  public ProfileId: string;
  public CompanyLogoUrl: string;
  public PostedDate: string;
  public PostedOn: string;
  public PostedBy: string;
  public ModifiedDate: string;
  public ExpiryDate: string;
  public MatchPercent: string;
  public Keywords: string;
  public ProfilePic:string;
  public ShortListedCount: string;
  public TotalViewCount:string;
  public HiringLeaderName:string;
  public UserRole:string;
  public InterviewedCount:string;
  public DislikesCount:string;
  public LikesCount:string;
  public TotalApplicants: string;
  public SkilledApplicants: string;
  public IsActive: false;
  public JobStatus: string;
  public JobActivity: JobActivity;
  public EducationDetails: EducationDetails[];
  public JobLocations: JobLocations;
}
