export class Settings {
  
  ProfilebaseUrl: string;
  IdentitybaseUrl: string;
  RefralbaseUrl: string;
  JobbaseUrl: string;
  SharingbaseUrl: string;
  EmailbaseUrl: string;
  GetInviteList:string;
  jobTitleEndpoint: string;
  getskillsEndpoint: string;
  addSkillsEndpoint: string;
  GetPersonTypeEndPoint: string;
  GetInterViewList: string;
  JobShareInvite: string;
  CustomerInterviewAccept: string;
  // locationwisejobtitlesendpoint: "http://api.tenendus.com:1090/JobsAPI/api/GetLocationWiseJobsCount",
  SuggestJobTitleEndPoint: string;
  SuggestJobCategoryEndPoint: string;
  draftCategory: string;
  educationcriteriaendpoint: string;
  addneweducationEndpoint: string;
  employmentTypeendpoint: string;
  salaryTypeendpoint: string;
  contractDurationendpoint: string;
  workAuthorizationendpoint: string;
  interviewtypeendpoint: string;
  NotificationEndPoint: string;
  GetCustomerContacts: string;
  listofJobsEndpoint: string;
  activatejobEndpoint: string;
  deactivatejobEndpoint: string;
  JobDetailsofCustomer: string;
  GetUserId: string;
  discTestEndpoint: string;
  updateemail: string;
  updatepassword: string;
  // interviewProcess : 'http://localhost:54226/api/ScheduleInterview',
  Login: string;
  ForgotPassword: string;
  ResetPassword: string;
  CustomerTokenLogin:  string;
  CustomerAppLogin: string;
  InviteContact: string;
  ProfileShareInvite: string;
  StartConversation: string;
  UpdateStatusOnEmailConversation: string;
  signUp: string;
  postjob: string;
  addRoles: string;
  getRoles: string;
  bulkResponsibilities: string;
  getJobResponsibilities: string;
  domaincriteriaendpoint: string;
  getCustomerUsersendpoint: string;
  DeleteShareContactInfo: string;
  GetCustomerContactsShareInfo: string;
  customerPreferredLocationendpoint: string;
  customerPreferredLocationendList: string;
  getCitiesendpoint: string;
  jobCategoryEndpoint: string;
  profileLink: string;
  scheduleInterview: string;
  UpdateScheduleInterview: string;
  EmailVaild: string;
  EmailInvite: string;
  ActivateUser: string;
  Deletedraft: string;
  ValidateUser: string;
  GetCustomerClients: string;
  getDraftClient: string;
  GetInterviewDetails:string;
  GetCustomerDepartments: string;
  GetJobDepartment: string;
  SendJobStatus:string;
  SendJobInterviewStatus:string;
 // SearchClients: 'http://api.tenendus.com:1090/ProfileAPI/api/SearchClients',
  // SearchDepartments: 'http://api.tenendus.com:1090/ProfileAPI/api/SearchDepartments',
 // postjob : 'http://api.tenendus.com:1090/JobsAPI/api/CreateJob?',
  searchclientsendpoint: string;
  searchdepartmentendpoint: string;
  SearchProfile: string;
  JobdetailsBasicInfoEndpoint: string;
  JobdetailsStatisticsEndpoint: string;
  JobdetailsProfileEndpoint: string;
  MatchingDetailEndPoint: string;
   VideoProfileEndPoint: string;
  GetAutoSearch: string;
  GetInterviewAutoSearch: string;
  GetJobsFilterBy: string;
  GetProfileAutoSearch: string;
  GetCitySearch: string;
  JobdetailsSuggestedProfileEndpoint: string;
  GetInterviewAccept: string;
  UpdateWishlist: string;
  RecentJobs: string;
  RecentApplicants: string;
  DashboardStatistics: string;
  ApplicantStatistics: string;
  CompanyProfileBasicInfo: string;
  CompanyProfileOtherInfo: string;
  GetAboutCompany: string;
  GetCompanyLogo: string;
  ActivateCustomerUser: string;
  UpdateFullName:string;
  InsertCustomerUser: string;
  CompanyTechnologies: string;
  CompanySpecialities: string;
  CompanyWhitePapers: string;
  ComapnyAchivements: string;
  CompanyPartnerships: string;
  CompanyCertifications: string;
  CompanyCultures: string;
  CompanyNewsPapers: string;
  GetCompanyBenfits: string;
  JobsProfileCount: string;
  SuggestedCount:string;
  GetJobDetialCustomerComments: string;
  GetJobTemplates: string;
  // CompanyProfileLocationInfo: 'http://api.tenendus.com:1090/JobsAPI/api/GetCustomerPreferredLocation?',
  EditDraft: string;
  InterviewScheduleType: string;
  profilesSortBy: string;
  SearchCandidateProfiles: string;
  DeleteCustomerClients: string;
  DeleteCustomerDepartments: string;
  DeleteCustomerLocation: string;
  baseUrll: string;
  AddContactShareInfo: string;
  bulkApply: string;
  WishlistCount: string;
  GetCustomerUsers: string;
  AddDepartment: string;
  customerLogin: string;
  customerSignUp: string;
  ForgotPasswordurl: string;
  CandidateSignUp: string;
  CandidateLogin: string;
  JobMatchingParameter: string;
  Arytic: string;
  QuestionbaseUrl:string;
  QuestionResult:string;
  GetPlans:string;
  AddPlan:string;
  GetPlanDuration:string;
  PlanUpdate:string;
  BillingEstimateDetails:string;
  BillingContactDetails:string;
  UnbillingChargeDetails:string;
  GetInvociePdf:string;
  BillingCardDetails:string;
  GetCustomerSubscription:string;
  GetSubscriptionDetails:string;
  GetCustomerInvoices:string;
  GetCustomerInvoicesPending:string;
  CustomerAddonCharge:string;
  GetJobMatchingCriteriaEndPoint: string;
  GetBillingAddressCustomer:string;
  GetDashboardStatisticsForJobsPosted:string;
  GetDashboardStatisticsForJobsFilled:string;
  GetDashboardStatisticsForJobsCancelled:string;
  GetCustomerApplicantsStatistics:string;
  GetCustomerShortListedStatistics:string;
  GetCustomerInterviewStatistics:string;
  GetCustomerHiredStatistics:string;
  GetJobLocationbyJobId:string;
  ReportingTeam:string;
  DeleteJobResponsibility:string;
  GetjobImps:string;
  GetCompanySize:string;
  GetDueDateList:string;
  GetImmigrationList:string;
  SaveJobImmigration:string;
  SaveJobResponseRoles:string;
  listofFilteredJobs : string;
  listofAllSkills : string;
  listofAllTitles : string;
  GetDeafultTemplates:string;
  GetCustomerWeekReport:string;
  GetCustomerMonthReport:string;
  GetCustomerYearReport:string;
  SaveJobFilter:string;
  GetSavedJobFilter:string;
  DeleteJobFilter:string;
  GetCustomerYearReportAll:string;
  GetCustomerApplicantYearReportAll:string;
  GetCustomerApplicantYear:string;
  GetCustomerApplicantWeek:string;
  GetCustomerApplicantMonth:string;
  GetCustomerInvitedUsers:string;
  GetUserLevelAccess:string;
  GetUserRoleAccess:string;
  CandidateAppLogin:string;
  InsertInviteCustomerUsers:string;
  DeleteCustomerInvitedUsers:string;
  GetUserDetail:string;
  ActivateCustomerInvitedUsers:string;
  CheckAndProvideAccess:string;
  GetReportingTeamList:string;
  GetTechinicalTeamList:string;
  GetRecruiterTeamList:string;
  SaveRecruiterTeamList:string;
  CustomerRequestRefernce:string;
  Indusrties:string;
  PositionTypes:string;
  Categories:string;
  TitleInfo:string;
  KeyResponses:string;
  CustomerIndustries:string;
  AddIndustry:string;
  AddPosition:string;
  AddCategory:string;
  AddJobTitle:string;
  AddKeyResponsibilities:string;
  GetAllCities:string;
  DeleteSavedFilter:string;
  InsertProfileNotesCustomer:string;
  GetProfileNotes:string;
  Attachments:string;
  DeleteNote:string;
  GetgoogleApi:string;
  GetProfileFeedback:string;
  }
