export class Settings {
  
  ProfilebaseUrl: string;
  IdentitybaseUrl: string;
  RefralbaseUrl: string;
  JobbaseUrl: string;
  SharingbaseUrl: string;
  EmailbaseUrl: string;
  GetInviteList:string;
  jobTitleEndpoint: string;
  getskillsEndpoint: string;
  addSkillsEndpoint: string;
  GetPersonTypeEndPoint: string;
  GetInterViewList: string;
  JobShareInvite: string;
  CustomerInterviewAccept: string;
  // locationwisejobtitlesendpoint: "http://api.tenendus.com:1090/JobsAPI/api/GetLocationWiseJobsCount",
  SuggestJobTitleEndPoint: string;
  SuggestJobCategoryEndPoint: string;
  draftCategory: string;
  educationcriteriaendpoint: string;
  addneweducationEndpoint: string;
  employmentTypeendpoint: string;
  salaryTypeendpoint: string;
  contractDurationendpoint: string;
  workAuthorizationendpoint: string;
  interviewtypeendpoint: string;
  NotificationEndPoint: string;
  GetCustomerContacts: string;
  listofJobsEndpoint: string;
  activatejobEndpoint: string;
  deactivatejobEndpoint: string;
  JobDetailsofCustomer: string;
  GetUserId: string;
  discTestEndpoint: string;
  updateemail: string;
  updatepassword: string;
  // interviewProcess : 'http://localhost:54226/api/ScheduleInterview',
  Login: string;
  ForgotPassword: string;
  ResetPassword: string;
  CustomerTokenLogin:  string;
  CustomerAppLogin: string;
  InviteContact: string;
  ProfileShareInvite: string;
  StartConversation: string;
  UpdateStatusOnEmailConversation: string;
  signUp: string;
  postjob: string;
  addRoles: string;
  getRoles: string;
  bulkResponsibilities: string;
  getJobResponsibilities: string;
  domaincriteriaendpoint: string;
  getCustomerUsersendpoint: string;
  DeleteShareContactInfo: string;
  GetCustomerContactsShareInfo: string;
  customerPreferredLocationendpoint: string;
  customerPreferredLocationendList: string;
  getCitiesendpoint: string;
  jobCategoryEndpoint: string;
  profileLink: string;
  scheduleInterview: string;
  UpdateScheduleInterview: string;
  EmailVaild: string;
  EmailInvite: string;
  ActivateUser: string;
  Deletedraft: string;
  ValidateUser: string;
  GetCustomerClients: string;
  getDraftClient: string;
  GetInterviewDetails:string;
  GetCustomerDepartments: string;
  GetJobDepartment: string;
 // SearchClients: 'http://api.tenendus.com:1090/ProfileAPI/api/SearchClients',
  // SearchDepartments: 'http://api.tenendus.com:1090/ProfileAPI/api/SearchDepartments',
 // postjob : 'http://api.tenendus.com:1090/JobsAPI/api/CreateJob?',
  searchclientsendpoint: string;
  searchdepartmentendpoint: string;
  SearchProfile: string;
  JobdetailsBasicInfoEndpoint: string;
  JobdetailsStatisticsEndpoint: string;
  JobdetailsProfileEndpoint: string;
  MatchingDetailEndPoint: string;
   VideoProfileEndPoint: string;
  GetAutoSearch: string;
  GetInterviewAutoSearch: string;
  GetJobsFilterBy: string;
  GetProfileAutoSearch: string;
  GetCitySearch: string;
  JobdetailsSuggestedProfileEndpoint: string;
  GetInterviewAccept: string;
  UpdateWishlist: string;
  RecentJobs: string;
  RecentApplicants: string;
  DashboardStatistics: string;
  ApplicantStatistics: string;
  CompanyProfileBasicInfo: string;
  CompanyProfileOtherInfo: string;
  GetAboutCompany: string;
  GetCompanyLogo: string;
  ActivateCustomerUser: string;
  InsertCustomerUser: string;
  CompanyTechnologies: string;
  CompanySpecialities: string;
  CompanyWhitePapers: string;
  ComapnyAchivements: string;
  CompanyPartnerships: string;
  CompanyCertifications: string;
  CompanyCultures: string;
  CompanyNewsPapers: string;
  GetCompanyBenfits: string;
  JobsProfileCount: string;
  GetJobDetialCustomerComments: string;
  GetJobTemplates: string;
  // CompanyProfileLocationInfo: 'http://api.tenendus.com:1090/JobsAPI/api/GetCustomerPreferredLocation?',
  EditDraft: string;
  InterviewScheduleType: string;
  profilesSortBy: string;
  SearchCandidateProfiles: string;
  DeleteCustomerClients: string;
  DeleteCustomerDepartments: string;
  DeleteCustomerLocation: string;
  baseUrll: string;
  AddContactShareInfo: string;
  bulkApply: string;
  WishlistCount: string;
  GetCustomerUsers: string;
  AddDepartment: string;
  customerLogin: string;
  customerSignUp: string;
  ForgotPasswordurl: string;
  CandidateSignUp: string;
  CandidateLogin: string;
  JobMatchingParameter: string;
  Arytic: string;
  QuestionbaseUrl:string;
  QuestionResult:string;
  GetPlans:string;
  AddPlan:string;
  GetPlanDuration:string;
  PlanUpdate:string;
  BillingEstimateDetails:string;
  BillingContactDetails:string;
  UnbillingChargeDetails:string;
  BillingCardDetails:string;
  GetCustomerSubscription:string;
  GetSubscriptionDetails:string;
  }
