export class getBillingContactDetails
{
    id:string;
    firstName:string;
    lastName:string;
    email:string;
    phone:string;
    company:string;
    vatNumber:string;
    autoCollection:number;
    netTermDays:number;
    vatNumberValidatedTime:string;
    vatNumberStatus:number;
    allowDirectDebit:boolean;
    isLocationValid:string;
    createdAt:Date;
    createdFromIp:string;
    exemptionDetails:string;
    taxability:number;
    entityCode:number;
    exemptNumber:string;
    resourceVersion:number;
    updatedAt:string;
    locale:string;
    consolidatedInvoicing:string;
    billingDate:string;
    billingDateMode:number;
    billingDayOfWeek:number;
    billingDayOfWeekMode:number;
    piiCleared:number;
    cardStatus:number;
    fraudFlag:number;
    primaryPaymentSourceId:string;
    backupPaymentSourceId:string;
    billingAddress:string;
    referralUrls:string;
    contacts:string;
    paymentMethod:string;
    invoiceNotes:string;
    preferredCurrencyCode:string
    promotionalCredits:number;
    unbilledCharges:number;
    refundableCredits:number;
    excessPayments:number;
    balances:string;
    metaData:string;
    deleted:boolean;
    registeredForGst:string;
    businessCustomerWithoutVatNumber:string;
    customerType:number;
    clientProfileId:string;
    relationship:string
}