import { JobLocations } from "./joblocations";
import {JobRequiredDomain} from "./JobRequiredDomain";
import {JobRequiredSkills} from './JobRequiredSkills';
import {JobResponsibility} from './JobResponsibility';

export class GetJobDetailCustomer
{
    JobInfoId: number;
    JobId: number;
    JobPositionId: number;
    UserId:number;
    CustomerId: number;
    JobCategoryId: number;
    JobCategory: string;
    JobTitle: string;
    MinExperienceId: number;
    MaxExperienceId: number;
    MinExperience: number;
    MaxExperience: number;
    CompleteDescription:string;
    JobDescription: string;
    NumberOfVacancies: number;
    EmploymentTypeId: number;
    EmploymentType: string;
    SalaryTypeId: number;
    SalaryType: string;
    MinimumSalary: string;
    MaximumSalary: string;
    BonusOffered: string;
    ContractDuration: string;
    ContractExtended: string;
    PossibilityOfFullTime: string;
    AfterWhatDuration: string;
    InterviewType:string;
    HiringProcessId: number;
    HiringManagerId: number;
    ReportingManager: string;
    IsActive: boolean;
    StatusId: number;
    FirstName: string;
    LastName: string;
    EmailId: string;
    PhoneNumber: string;
    CompanyName: string;
    CompanyDescription:string;
    CompanyLogo: string;
    WebSite: string;
    FromTime: string;
    ToTime: string;
    TimeZoneId: string;
    TimeZone: string;
    PostedOn: string;
    ModifiedDate: string;
    PostedBy: string;
    ExpiryDate: string;
    SaveAsTemplate: string;
    RemoteWorkId: number;
    RemoteWorkType: string;
    Travel: string;
    TravelPercentage: string;
    IsPrivate: boolean;
    JobAccessTo: string;
    JobStatus: string;
    JobLocation: JobLocations;
    JobRequiredDomain: JobRequiredDomain;
    JobRequiredSkills:JobRequiredSkills;
    JobResponsibility:JobResponsibility;
}